export default {
  name: "COMMUNITY",
  subtitle: "Yoga",
  tagline: "Real Community. Real Yoga.",
  city: "Charleston, SC",
  logoMark: "CY",
  logoUrl: "https://images.squarespace-cdn.com/content/v1/584ae440414fb58b69f4d708/81c57f87-109b-4f6a-9b69-c038bec2da00/LOGO2LT.png?format=300w",
  accent: "#2a7a8a",
  accentLight: "#e8f2f4",
  displayFont: "Cormorant Garamond",
  classCount: "35+",
  teacherCount: "8",
  memberTier: "Monthly Unlimited",
  features: [
  { title: "Class Scheduling", desc: "Weekly schedule with real-time reservations" },
  { title: "Practice Tracking", desc: "Reflections, streaks, and milestone badges" },
  { title: "Community Feed", desc: "Member milestones and celebrations" },
  { title: "Teacher Profiles", desc: "Bios, certifications, and specialties" },
  { title: "Membership Tiers", desc: "7 plans from intro to annual" },
  { title: "Events & Workshops", desc: "Soul Sundays, sound baths, and workshops" },
  { title: "Smart Notifications", desc: "Class reminders and streak alerts" },
  { title: "Admin Dashboard", desc: "Full analytics, CRM, and broadcast tools" },
  ],
  salesCards: [
  { title: "Admin Dashboard", desc: "Tap the shield icon in the app header to access the full admin suite — analytics, member CRM, scheduling, and broadcast tools." },
  { title: "Built for COMMUNITY Yoga", desc: "Custom-built for this specific studio — designed around your brand, class types, teachers, and the welcoming community your members already love." },
  { title: "All-in-One Platform", desc: "Handles booking, payments, and member management natively — no third-party software needed." },
  { title: "Member Engagement", desc: "Practice streaks, milestone badges, guest passes, and a community feed keep members connected between classes." },
  { title: "Custom-Built for You", desc: "Your brand, your colors, your identity — deployed as a standalone app purpose-built specifically for your studio." },
  ],
};
